/**
 * Configuración centralizada de endpoints de la API
 * Este archivo define todas las rutas de la API utilizadas en la aplicación
 */

import ENV from '../config/environment';

const config = {
  API: {
    BASE_URL: ENV.API_URL,
    TIMEOUT: ENV.API_TIMEOUT,
    RETRY_ATTEMPTS: ENV.API_RETRY_ATTEMPTS
  },
  
  AUTH: {
    LOGIN: ENV.ROUTES.AUTH.LOGIN,
    REGISTER: ENV.ROUTES.AUTH.REGISTER,
    VERIFY: ENV.ROUTES.AUTH.VERIFY,
    USER: ENV.ROUTES.AUTH.USER
  },
  
  EXPENSES: {
    MONTHLY: ENV.ROUTES.PERSONAL_EXPENSES.MONTHLY,
    BASE: ENV.ROUTES.PERSONAL_EXPENSES.BASE,
    FILTERED: ENV.ROUTES.PERSONAL_EXPENSES.FILTERED,
    DETAIL: ENV.ROUTES.PERSONAL_EXPENSES.DETAIL
  },
  
  PERSONAL_EXPENSES: {
    BASE: ENV.ROUTES.PERSONAL_EXPENSES.BASE,
    MONTHLY: ENV.ROUTES.PERSONAL_EXPENSES.MONTHLY,
    FILTERED: ENV.ROUTES.PERSONAL_EXPENSES.FILTERED,
    GENERATE_SHARED: ENV.ROUTES.PERSONAL_EXPENSES.GENERATE_SHARED,
    CREATE: ENV.ROUTES.PERSONAL_EXPENSES.BASE,
    UPDATE: ENV.ROUTES.PERSONAL_EXPENSES.DETAIL,
    DELETE: ENV.ROUTES.PERSONAL_EXPENSES.DETAIL,
    SHARED_SUMMARY: ENV.ROUTES.PERSONAL_EXPENSES.GENERATE_SHARED
  },
  
  INCOME: {
    MONTHLY: ENV.ROUTES.INCOME.MONTHLY,
    BASE: ENV.ROUTES.INCOME.BASE,
    DETAIL: ENV.ROUTES.INCOME.DETAIL
  },
  
  SHARED: {
    BASE: ENV.ROUTES.SHARED_SESSIONS.BASE,
    DETAIL: ENV.ROUTES.SHARED_SESSIONS.DETAIL,
    EXPENSES: ENV.ROUTES.SHARED_SESSIONS.EXPENSES,
    EXPENSE: ENV.ROUTES.SHARED_SESSIONS.EXPENSE,
    SYNC_TO_PERSONAL: ENV.ROUTES.SHARED_SESSIONS.SYNC_TO_PERSONAL
  },
  
  REPORTS: {
    SUMMARY: ENV.ROUTES.REPORTS.SUMMARY,
    MONTHLY: ENV.ROUTES.REPORTS.MONTHLY,
    YEARLY: ENV.ROUTES.REPORTS.YEARLY
  },
  
  HEALTH: ENV.ROUTES.API.HEALTH
};

export default config; 